# Generated by Django 3.2.2 on 2021-06-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('p_idx', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=10000000000)),
            ],
        ),
    ]
